// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVMsVM28MUJ64M_2c-syAs_SrXwL4PiYQ',
    appId: '1:52176589302:web:e588506badcc2651df37d7',
    messagingSenderId: '52176589302',
    projectId: 'estore-20cbc',
    authDomain: 'estore-20cbc.firebaseapp.com',
    storageBucket: 'estore-20cbc.appspot.com',
    measurementId: 'G-2WTF8Z5591',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzR1u_xqk2eO-bKCtwmQU47lq_tvISXc4',
    appId: '1:52176589302:android:03b223c9e0748c6bdf37d7',
    messagingSenderId: '52176589302',
    projectId: 'estore-20cbc',
    storageBucket: 'estore-20cbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZA_d5dSmo-DBrFR0PBwnA-9OMfVIe2lw',
    appId: '1:52176589302:ios:0b6c40a49e4cd365df37d7',
    messagingSenderId: '52176589302',
    projectId: 'estore-20cbc',
    storageBucket: 'estore-20cbc.appspot.com',
    iosClientId: '52176589302-u55cdci56k1tu97509hltbvb8pobfll8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZA_d5dSmo-DBrFR0PBwnA-9OMfVIe2lw',
    appId: '1:52176589302:ios:0b6c40a49e4cd365df37d7',
    messagingSenderId: '52176589302',
    projectId: 'estore-20cbc',
    storageBucket: 'estore-20cbc.appspot.com',
    iosClientId: '52176589302-u55cdci56k1tu97509hltbvb8pobfll8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
